package com.autobid.model;

import java.util.Date;

public class BidList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.listing_id
     *
     * @mbggenerated
     */
    private Integer listingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.debt_id
     *
     * @mbggenerated
     */
    private Integer debtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.price_for_sale_rate
     *
     * @mbggenerated
     */
    private Integer priceForSaleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.credit_code
     *
     * @mbggenerated
     */
    private String creditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.bid_time
     *
     * @mbggenerated
     */
    private Date bidTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.id
     *
     * @return the value of bid_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.id
     *
     * @param id the value for bid_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.listing_id
     *
     * @return the value of bid_list.listing_id
     *
     * @mbggenerated
     */
    public Integer getListingId() {
        return listingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.listing_id
     *
     * @param listingId the value for bid_list.listing_id
     *
     * @mbggenerated
     */
    public void setListingId(Integer listingId) {
        this.listingId = listingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.debt_id
     *
     * @return the value of bid_list.debt_id
     *
     * @mbggenerated
     */
    public Integer getDebtId() {
        return debtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.debt_id
     *
     * @param debtId the value for bid_list.debt_id
     *
     * @mbggenerated
     */
    public void setDebtId(Integer debtId) {
        this.debtId = debtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.amount
     *
     * @return the value of bid_list.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.amount
     *
     * @param amount the value for bid_list.amount
     *
     * @mbggenerated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.price_for_sale_rate
     *
     * @return the value of bid_list.price_for_sale_rate
     *
     * @mbggenerated
     */
    public Integer getPriceForSaleRate() {
        return priceForSaleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.price_for_sale_rate
     *
     * @param priceForSaleRate the value for bid_list.price_for_sale_rate
     *
     * @mbggenerated
     */
    public void setPriceForSaleRate(Integer priceForSaleRate) {
        this.priceForSaleRate = priceForSaleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.credit_code
     *
     * @return the value of bid_list.credit_code
     *
     * @mbggenerated
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.credit_code
     *
     * @param creditCode the value for bid_list.credit_code
     *
     * @mbggenerated
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.bid_time
     *
     * @return the value of bid_list.bid_time
     *
     * @mbggenerated
     */
    public Date getBidTime() {
        return bidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.bid_time
     *
     * @param bidTime the value for bid_list.bid_time
     *
     * @mbggenerated
     */
    public void setBidTime(Date bidTime) {
        this.bidTime = bidTime;
    }
}