package com.autobid.model;

import java.util.Date;

public class LoanInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.first_bid_time
     *
     * @mbggenerated
     */
    private Date firstBidTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.last_bid_time
     *
     * @mbggenerated
     */
    private Date lastBidTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.lender_count
     *
     * @mbggenerated
     */
    private Integer lenderCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.auditing_time
     *
     * @mbggenerated
     */
    private Date auditingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.remain_funding
     *
     * @mbggenerated
     */
    private Long remainFunding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.dead_line_time_or_remind_time_str
     *
     * @mbggenerated
     */
    private String deadLineTimeOrRemindTimeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.credit_code
     *
     * @mbggenerated
     */
    private String creditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.listing_id
     *
     * @mbggenerated
     */
    private Integer listingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.amount
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.mounths
     *
     * @mbggenerated
     */
    private Integer mounths;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.current_rate
     *
     * @mbggenerated
     */
    private Double currentRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.borrow_name
     *
     * @mbggenerated
     */
    private String borrowName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.gender
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.education_degree
     *
     * @mbggenerated
     */
    private String educationDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.graduate_school
     *
     * @mbggenerated
     */
    private String graduateSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.stydy_style
     *
     * @mbggenerated
     */
    private String stydyStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.success_count
     *
     * @mbggenerated
     */
    private Integer successCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.waste_count
     *
     * @mbggenerated
     */
    private Integer wasteCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.cancel_count
     *
     * @mbggenerated
     */
    private Integer cancelCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.failed_count
     *
     * @mbggenerated
     */
    private Integer failedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.normal_count
     *
     * @mbggenerated
     */
    private Integer normalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.overdue_less_count
     *
     * @mbggenerated
     */
    private Integer overdueLessCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.overdue_more_count
     *
     * @mbggenerated
     */
    private Integer overdueMoreCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.owing_principal
     *
     * @mbggenerated
     */
    private Integer owingPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.owing_amount
     *
     * @mbggenerated
     */
    private Integer owingAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.amount_to_receive
     *
     * @mbggenerated
     */
    private Integer amountToReceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.first_success_borrow_time
     *
     * @mbggenerated
     */
    private Date firstSuccessBorrowTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.certificate_validate
     *
     * @mbggenerated
     */
    private Integer certificateValidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.nciic_identity_check
     *
     * @mbggenerated
     */
    private Integer nciicIdentityCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.phone_validate
     *
     * @mbggenerated
     */
    private Integer phoneValidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.video_validate
     *
     * @mbggenerated
     */
    private Integer videoValidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.credit_validate
     *
     * @mbggenerated
     */
    private Integer creditValidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.educate_validate
     *
     * @mbggenerated
     */
    private Integer educateValidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.last_success_borrow_time
     *
     * @mbggenerated
     */
    private Date lastSuccessBorrowTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.highest_principal
     *
     * @mbggenerated
     */
    private Long highestPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.highest_debt
     *
     * @mbggenerated
     */
    private Long highestDebt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.total_principal
     *
     * @mbggenerated
     */
    private Long totalPrincipal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.id
     *
     * @return the value of loan_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.id
     *
     * @param id the value for loan_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.first_bid_time
     *
     * @return the value of loan_info.first_bid_time
     *
     * @mbggenerated
     */
    public Date getFirstBidTime() {
        return firstBidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.first_bid_time
     *
     * @param firstBidTime the value for loan_info.first_bid_time
     *
     * @mbggenerated
     */
    public void setFirstBidTime(Date firstBidTime) {
        this.firstBidTime = firstBidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.last_bid_time
     *
     * @return the value of loan_info.last_bid_time
     *
     * @mbggenerated
     */
    public Date getLastBidTime() {
        return lastBidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.last_bid_time
     *
     * @param lastBidTime the value for loan_info.last_bid_time
     *
     * @mbggenerated
     */
    public void setLastBidTime(Date lastBidTime) {
        this.lastBidTime = lastBidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.lender_count
     *
     * @return the value of loan_info.lender_count
     *
     * @mbggenerated
     */
    public Integer getLenderCount() {
        return lenderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.lender_count
     *
     * @param lenderCount the value for loan_info.lender_count
     *
     * @mbggenerated
     */
    public void setLenderCount(Integer lenderCount) {
        this.lenderCount = lenderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.auditing_time
     *
     * @return the value of loan_info.auditing_time
     *
     * @mbggenerated
     */
    public Date getAuditingTime() {
        return auditingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.auditing_time
     *
     * @param auditingTime the value for loan_info.auditing_time
     *
     * @mbggenerated
     */
    public void setAuditingTime(Date auditingTime) {
        this.auditingTime = auditingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.remain_funding
     *
     * @return the value of loan_info.remain_funding
     *
     * @mbggenerated
     */
    public Long getRemainFunding() {
        return remainFunding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.remain_funding
     *
     * @param remainFunding the value for loan_info.remain_funding
     *
     * @mbggenerated
     */
    public void setRemainFunding(Long remainFunding) {
        this.remainFunding = remainFunding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.dead_line_time_or_remind_time_str
     *
     * @return the value of loan_info.dead_line_time_or_remind_time_str
     *
     * @mbggenerated
     */
    public String getDeadLineTimeOrRemindTimeStr() {
        return deadLineTimeOrRemindTimeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.dead_line_time_or_remind_time_str
     *
     * @param deadLineTimeOrRemindTimeStr the value for loan_info.dead_line_time_or_remind_time_str
     *
     * @mbggenerated
     */
    public void setDeadLineTimeOrRemindTimeStr(String deadLineTimeOrRemindTimeStr) {
        this.deadLineTimeOrRemindTimeStr = deadLineTimeOrRemindTimeStr == null ? null : deadLineTimeOrRemindTimeStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.credit_code
     *
     * @return the value of loan_info.credit_code
     *
     * @mbggenerated
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.credit_code
     *
     * @param creditCode the value for loan_info.credit_code
     *
     * @mbggenerated
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.listing_id
     *
     * @return the value of loan_info.listing_id
     *
     * @mbggenerated
     */
    public Integer getListingId() {
        return listingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.listing_id
     *
     * @param listingId the value for loan_info.listing_id
     *
     * @mbggenerated
     */
    public void setListingId(Integer listingId) {
        this.listingId = listingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.amount
     *
     * @return the value of loan_info.amount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.amount
     *
     * @param amount the value for loan_info.amount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.mounths
     *
     * @return the value of loan_info.mounths
     *
     * @mbggenerated
     */
    public Integer getMounths() {
        return mounths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.mounths
     *
     * @param mounths the value for loan_info.mounths
     *
     * @mbggenerated
     */
    public void setMounths(Integer mounths) {
        this.mounths = mounths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.current_rate
     *
     * @return the value of loan_info.current_rate
     *
     * @mbggenerated
     */
    public Double getCurrentRate() {
        return currentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.current_rate
     *
     * @param currentRate the value for loan_info.current_rate
     *
     * @mbggenerated
     */
    public void setCurrentRate(Double currentRate) {
        this.currentRate = currentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.borrow_name
     *
     * @return the value of loan_info.borrow_name
     *
     * @mbggenerated
     */
    public String getBorrowName() {
        return borrowName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.borrow_name
     *
     * @param borrowName the value for loan_info.borrow_name
     *
     * @mbggenerated
     */
    public void setBorrowName(String borrowName) {
        this.borrowName = borrowName == null ? null : borrowName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.gender
     *
     * @return the value of loan_info.gender
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.gender
     *
     * @param gender the value for loan_info.gender
     *
     * @mbggenerated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.education_degree
     *
     * @return the value of loan_info.education_degree
     *
     * @mbggenerated
     */
    public String getEducationDegree() {
        return educationDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.education_degree
     *
     * @param educationDegree the value for loan_info.education_degree
     *
     * @mbggenerated
     */
    public void setEducationDegree(String educationDegree) {
        this.educationDegree = educationDegree == null ? null : educationDegree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.graduate_school
     *
     * @return the value of loan_info.graduate_school
     *
     * @mbggenerated
     */
    public String getGraduateSchool() {
        return graduateSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.graduate_school
     *
     * @param graduateSchool the value for loan_info.graduate_school
     *
     * @mbggenerated
     */
    public void setGraduateSchool(String graduateSchool) {
        this.graduateSchool = graduateSchool == null ? null : graduateSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.stydy_style
     *
     * @return the value of loan_info.stydy_style
     *
     * @mbggenerated
     */
    public String getStydyStyle() {
        return stydyStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.stydy_style
     *
     * @param stydyStyle the value for loan_info.stydy_style
     *
     * @mbggenerated
     */
    public void setStydyStyle(String stydyStyle) {
        this.stydyStyle = stydyStyle == null ? null : stydyStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.age
     *
     * @return the value of loan_info.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.age
     *
     * @param age the value for loan_info.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.success_count
     *
     * @return the value of loan_info.success_count
     *
     * @mbggenerated
     */
    public Integer getSuccessCount() {
        return successCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.success_count
     *
     * @param successCount the value for loan_info.success_count
     *
     * @mbggenerated
     */
    public void setSuccessCount(Integer successCount) {
        this.successCount = successCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.waste_count
     *
     * @return the value of loan_info.waste_count
     *
     * @mbggenerated
     */
    public Integer getWasteCount() {
        return wasteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.waste_count
     *
     * @param wasteCount the value for loan_info.waste_count
     *
     * @mbggenerated
     */
    public void setWasteCount(Integer wasteCount) {
        this.wasteCount = wasteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.cancel_count
     *
     * @return the value of loan_info.cancel_count
     *
     * @mbggenerated
     */
    public Integer getCancelCount() {
        return cancelCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.cancel_count
     *
     * @param cancelCount the value for loan_info.cancel_count
     *
     * @mbggenerated
     */
    public void setCancelCount(Integer cancelCount) {
        this.cancelCount = cancelCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.failed_count
     *
     * @return the value of loan_info.failed_count
     *
     * @mbggenerated
     */
    public Integer getFailedCount() {
        return failedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.failed_count
     *
     * @param failedCount the value for loan_info.failed_count
     *
     * @mbggenerated
     */
    public void setFailedCount(Integer failedCount) {
        this.failedCount = failedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.normal_count
     *
     * @return the value of loan_info.normal_count
     *
     * @mbggenerated
     */
    public Integer getNormalCount() {
        return normalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.normal_count
     *
     * @param normalCount the value for loan_info.normal_count
     *
     * @mbggenerated
     */
    public void setNormalCount(Integer normalCount) {
        this.normalCount = normalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.overdue_less_count
     *
     * @return the value of loan_info.overdue_less_count
     *
     * @mbggenerated
     */
    public Integer getOverdueLessCount() {
        return overdueLessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.overdue_less_count
     *
     * @param overdueLessCount the value for loan_info.overdue_less_count
     *
     * @mbggenerated
     */
    public void setOverdueLessCount(Integer overdueLessCount) {
        this.overdueLessCount = overdueLessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.overdue_more_count
     *
     * @return the value of loan_info.overdue_more_count
     *
     * @mbggenerated
     */
    public Integer getOverdueMoreCount() {
        return overdueMoreCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.overdue_more_count
     *
     * @param overdueMoreCount the value for loan_info.overdue_more_count
     *
     * @mbggenerated
     */
    public void setOverdueMoreCount(Integer overdueMoreCount) {
        this.overdueMoreCount = overdueMoreCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.owing_principal
     *
     * @return the value of loan_info.owing_principal
     *
     * @mbggenerated
     */
    public Integer getOwingPrincipal() {
        return owingPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.owing_principal
     *
     * @param owingPrincipal the value for loan_info.owing_principal
     *
     * @mbggenerated
     */
    public void setOwingPrincipal(Integer owingPrincipal) {
        this.owingPrincipal = owingPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.owing_amount
     *
     * @return the value of loan_info.owing_amount
     *
     * @mbggenerated
     */
    public Integer getOwingAmount() {
        return owingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.owing_amount
     *
     * @param owingAmount the value for loan_info.owing_amount
     *
     * @mbggenerated
     */
    public void setOwingAmount(Integer owingAmount) {
        this.owingAmount = owingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.amount_to_receive
     *
     * @return the value of loan_info.amount_to_receive
     *
     * @mbggenerated
     */
    public Integer getAmountToReceive() {
        return amountToReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.amount_to_receive
     *
     * @param amountToReceive the value for loan_info.amount_to_receive
     *
     * @mbggenerated
     */
    public void setAmountToReceive(Integer amountToReceive) {
        this.amountToReceive = amountToReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.first_success_borrow_time
     *
     * @return the value of loan_info.first_success_borrow_time
     *
     * @mbggenerated
     */
    public Date getFirstSuccessBorrowTime() {
        return firstSuccessBorrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.first_success_borrow_time
     *
     * @param firstSuccessBorrowTime the value for loan_info.first_success_borrow_time
     *
     * @mbggenerated
     */
    public void setFirstSuccessBorrowTime(Date firstSuccessBorrowTime) {
        this.firstSuccessBorrowTime = firstSuccessBorrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.register_time
     *
     * @return the value of loan_info.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.register_time
     *
     * @param registerTime the value for loan_info.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.certificate_validate
     *
     * @return the value of loan_info.certificate_validate
     *
     * @mbggenerated
     */
    public Integer getCertificateValidate() {
        return certificateValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.certificate_validate
     *
     * @param certificateValidate the value for loan_info.certificate_validate
     *
     * @mbggenerated
     */
    public void setCertificateValidate(Integer certificateValidate) {
        this.certificateValidate = certificateValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.nciic_identity_check
     *
     * @return the value of loan_info.nciic_identity_check
     *
     * @mbggenerated
     */
    public Integer getNciicIdentityCheck() {
        return nciicIdentityCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.nciic_identity_check
     *
     * @param nciicIdentityCheck the value for loan_info.nciic_identity_check
     *
     * @mbggenerated
     */
    public void setNciicIdentityCheck(Integer nciicIdentityCheck) {
        this.nciicIdentityCheck = nciicIdentityCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.phone_validate
     *
     * @return the value of loan_info.phone_validate
     *
     * @mbggenerated
     */
    public Integer getPhoneValidate() {
        return phoneValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.phone_validate
     *
     * @param phoneValidate the value for loan_info.phone_validate
     *
     * @mbggenerated
     */
    public void setPhoneValidate(Integer phoneValidate) {
        this.phoneValidate = phoneValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.video_validate
     *
     * @return the value of loan_info.video_validate
     *
     * @mbggenerated
     */
    public Integer getVideoValidate() {
        return videoValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.video_validate
     *
     * @param videoValidate the value for loan_info.video_validate
     *
     * @mbggenerated
     */
    public void setVideoValidate(Integer videoValidate) {
        this.videoValidate = videoValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.credit_validate
     *
     * @return the value of loan_info.credit_validate
     *
     * @mbggenerated
     */
    public Integer getCreditValidate() {
        return creditValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.credit_validate
     *
     * @param creditValidate the value for loan_info.credit_validate
     *
     * @mbggenerated
     */
    public void setCreditValidate(Integer creditValidate) {
        this.creditValidate = creditValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.educate_validate
     *
     * @return the value of loan_info.educate_validate
     *
     * @mbggenerated
     */
    public Integer getEducateValidate() {
        return educateValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.educate_validate
     *
     * @param educateValidate the value for loan_info.educate_validate
     *
     * @mbggenerated
     */
    public void setEducateValidate(Integer educateValidate) {
        this.educateValidate = educateValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.last_success_borrow_time
     *
     * @return the value of loan_info.last_success_borrow_time
     *
     * @mbggenerated
     */
    public Date getLastSuccessBorrowTime() {
        return lastSuccessBorrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.last_success_borrow_time
     *
     * @param lastSuccessBorrowTime the value for loan_info.last_success_borrow_time
     *
     * @mbggenerated
     */
    public void setLastSuccessBorrowTime(Date lastSuccessBorrowTime) {
        this.lastSuccessBorrowTime = lastSuccessBorrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.highest_principal
     *
     * @return the value of loan_info.highest_principal
     *
     * @mbggenerated
     */
    public Long getHighestPrincipal() {
        return highestPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.highest_principal
     *
     * @param highestPrincipal the value for loan_info.highest_principal
     *
     * @mbggenerated
     */
    public void setHighestPrincipal(Long highestPrincipal) {
        this.highestPrincipal = highestPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.highest_debt
     *
     * @return the value of loan_info.highest_debt
     *
     * @mbggenerated
     */
    public Long getHighestDebt() {
        return highestDebt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.highest_debt
     *
     * @param highestDebt the value for loan_info.highest_debt
     *
     * @mbggenerated
     */
    public void setHighestDebt(Long highestDebt) {
        this.highestDebt = highestDebt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.total_principal
     *
     * @return the value of loan_info.total_principal
     *
     * @mbggenerated
     */
    public Long getTotalPrincipal() {
        return totalPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.total_principal
     *
     * @param totalPrincipal the value for loan_info.total_principal
     *
     * @mbggenerated
     */
    public void setTotalPrincipal(Long totalPrincipal) {
        this.totalPrincipal = totalPrincipal;
    }
}