package com.autobid.dao;

import com.autobid.model.BidList;
import java.util.List;

public interface BidListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid_list
     *
     * @mbggenerated
     */
    int insert(BidList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid_list
     *
     * @mbggenerated
     */
    BidList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid_list
     *
     * @mbggenerated
     */
    List<BidList> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BidList record);
}