package com.autobid.dao;

import com.autobid.model.DebtInfo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DebtInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("currentCreditCode") String currentCreditCode, @Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_info
     *
     * @mbggenerated
     */
    int insert(DebtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_info
     *
     * @mbggenerated
     */
    DebtInfo selectByPrimaryKey(@Param("currentCreditCode") String currentCreditCode, @Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_info
     *
     * @mbggenerated
     */
    List<DebtInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DebtInfo record);
}